"""add objective learning experiences

Revision ID: cap024
Revises: cap023
Create Date: 2026-08-03
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "cap024"
down_revision = "cap023"
branch_labels = None
depends_on = None


TABLE = "objective_learning_experiences"


def upgrade() -> None:
    op.create_table(
        TABLE,
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "tenant_id",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "resolution_record_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "objective_namespace",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column(
            "objective_type",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column(
            "objective_ref",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "objective_version",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "schema_ref",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "profile_ref",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "profile_version",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "extractor_ref",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "extractor_version",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "outcome_ref",
            sa.String(length=500),
            nullable=False,
        ),
        sa.Column(
            "evaluation_ref",
            sa.String(length=500),
            nullable=False,
        ),
        sa.Column(
            "workflow_run_id",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column(
            "dimension_keys_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "evidence_refs_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "validity_scope_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "experience_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "informational_only",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
        sa.Column(
            "authorizes_execution",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["resolution_record_id"],
            ["objective_resolution_records.id"],
            name=("fk_objective_learning_experiences_resolution_record"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=("pk_objective_learning_experiences"),
        ),
        sa.UniqueConstraint(
            "user_id",
            "resolution_record_id",
            "schema_ref",
            "profile_ref",
            "profile_version",
            "extractor_ref",
            "extractor_version",
            name=("uq_objective_learning_experiences_semantic_extraction"),
        ),
    )

    op.create_index(
        "ix_objective_learning_experiences_user_id",
        TABLE,
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_objective_learning_experiences_tenant_id",
        TABLE,
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_objective_learning_experiences_resolution_record_id",
        TABLE,
        ["resolution_record_id"],
        unique=False,
    )
    op.create_index(
        "ix_objective_learning_experiences_objective_namespace",
        TABLE,
        ["objective_namespace"],
        unique=False,
    )
    op.create_index(
        "ix_objective_learning_experiences_objective_type",
        TABLE,
        ["objective_type"],
        unique=False,
    )
    op.create_index(
        "ix_objective_learning_experiences_objective_ref",
        TABLE,
        ["objective_ref"],
        unique=False,
    )
    op.create_index(
        "ix_objective_learning_experiences_schema_ref",
        TABLE,
        ["schema_ref"],
        unique=False,
    )
    op.create_index(
        "ix_objective_learning_experiences_profile_ref",
        TABLE,
        ["profile_ref"],
        unique=False,
    )
    op.create_index(
        "ix_objective_learning_experiences_extractor_ref",
        TABLE,
        ["extractor_ref"],
        unique=False,
    )
    op.create_index(
        "ix_objective_learning_experiences_outcome_ref",
        TABLE,
        ["outcome_ref"],
        unique=False,
    )
    op.create_index(
        "ix_objective_learning_experiences_evaluation_ref",
        TABLE,
        ["evaluation_ref"],
        unique=False,
    )
    op.create_index(
        "ix_objective_learning_experiences_workflow_run_id",
        TABLE,
        ["workflow_run_id"],
        unique=False,
    )
    op.create_index(
        "ix_objective_learning_experiences_created_at",
        TABLE,
        ["created_at"],
        unique=False,
    )

    op.create_index(
        "ix_objective_learning_experiences_owner_created",
        TABLE,
        [
            "user_id",
            "tenant_id",
            "created_at",
        ],
        unique=False,
    )
    op.create_index(
        "ix_objective_learning_experiences_objective_created",
        TABLE,
        [
            "user_id",
            "objective_namespace",
            "objective_type",
            "objective_ref",
            "created_at",
        ],
        unique=False,
    )
    op.create_index(
        "ix_objective_learning_experiences_resolution_created",
        TABLE,
        [
            "resolution_record_id",
            "created_at",
        ],
        unique=False,
    )
    op.create_index(
        "ix_objective_learning_experiences_profile_extractor",
        TABLE,
        [
            "profile_ref",
            "profile_version",
            "extractor_ref",
            "extractor_version",
        ],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        "ix_objective_learning_experiences_profile_extractor",
        table_name=TABLE,
    )
    op.drop_index(
        "ix_objective_learning_experiences_resolution_created",
        table_name=TABLE,
    )
    op.drop_index(
        "ix_objective_learning_experiences_objective_created",
        table_name=TABLE,
    )
    op.drop_index(
        "ix_objective_learning_experiences_owner_created",
        table_name=TABLE,
    )

    for name in (
        "created_at",
        "workflow_run_id",
        "evaluation_ref",
        "outcome_ref",
        "extractor_ref",
        "profile_ref",
        "schema_ref",
        "objective_ref",
        "objective_type",
        "objective_namespace",
        "resolution_record_id",
        "tenant_id",
        "user_id",
    ):
        op.drop_index(
            f"ix_objective_learning_experiences_{name}",
            table_name=TABLE,
        )

    op.drop_table(TABLE)
